# --- Fonts ---
font_family      JetBrainsMono Nerd Font
# font_family      Noto Sans
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
modify_font line_height 110%
disable_ligatures cursor

# --- Cursor & Mouse ---
cursor #fe8019
cursor_text_color #282828
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0
shell_integration enabled
copy_on_select yes
focus_follows_mouse yes

# --- Window Layout ---
remember_window_size  yes
initial_window_width  1000
initial_window_height 650
window_padding_width 6
confirm_os_window_close 0

# --- Performance & Graphics ---
repaint_delay 10
input_delay 3
sync_to_monitor yes
background_opacity 0.6
background_blur 1

# --- Tab Bar ---
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
inactive_tab_font_style normal

# --- URL Handling ---
open_url_with default
detect_urls yes
underline_hyperlinks always

# --- Layout ---
enabled_layouts tall,stack,fat,grid

# --- Terminal Bell ---
enable_audio_bell no
visual_bell_duration 0.1

# --- Colors (Gruvbox Dark) ---
foreground            #ebdbb2
background            #282828
selection_foreground  #282828
selection_background  #ebdbb2
url_color             #83a598

# Black
color0  #282828
color8  #928374

# Red
color1  #cc241d
color9  #fb4934

# Green
color2  #98971a
color10 #b8bb26

# Yellow
color3  #d79921
color11 #fabd2f

# Blue
color4  #458588
color12 #83a598

# Magenta
color5  #b16286
color13 #d3869b

# Cyan
color6  #689d6a
color14 #8ec07c

# White
color7  #a89984
color15 #ebdbb2

# --- Keyboard Shortcuts ---
# Map Ctrl+Shift+h to open the entire scrollback buffer in Neovim
scrollback_pager nvim -c "set signcolumn=no showtabline=0" -c "silent! %s/\u001b\[[0-9;]*m//g" -c "normal G" -
scrollback_lines 2000
map ctrl+shift+h show_scrollback

# --- Tab Mappings ---
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+n next_tab
map alt+p previous_tab

# Quick-select and open URLs
map ctrl+shift+u kitten hints --type url

# Quick-select and copy paths to clipboard
map ctrl+shift+p kitten hints --type path --program @

# Reload config on the fly
map ctrl+shift+f5 load_config_file
