include ~/.cache/wal/colors-kitty.conf
# --- Fonts ---
font_family      JetBrainsMono Nerd Font
# font_family      Noto Sans
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
modify_font line_height 110%
disable_ligatures cursor
# --- Cursor & Mouse ---
cursor #88C0D0
cursor_text_color #2E3440
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0
shell_integration enabled
copy_on_select yes
focus_follows_mouse yes
# --- Window Layout ---
remember_window_size  yes
initial_window_width  1000
initial_window_height 650
window_padding_width 0 0 0 0 
window_padding_width 0
window_padding_height 0
confirm_os_window_close 0
# --- Performance & Graphics ---
# repaint_delay 10
# input_delay 3
sync_to_monitor yes
# extended_keys yes
background_opacity 0.8
dynamic_background_opacity yes
background_blur 1
# --- Tab Bar ---
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
active_tab_font_style bold
inactive_tab_font_style normal
# --- URL Handling ---
open_url_with default
detect_urls yes
underline_hyperlinks always
# --- Layout ---
enabled_layouts tall,stack,fat,grid
# --- Terminal Bell ---
enable_audio_bell no
visual_bell_duration 0.1
# --- Colors (Catppuccin Mocha) ---
foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #1e1e2e
selection_background  #f5e0dc
url_color             #f5e0dc
# Black
color0  #45475a
color8  #585b70
# Red
color1  #f38ba8
color9  #f38ba8
# Green
color2  #a6e3a1
color10 #a6e3a1
# Yellow
color3  #f9e2af
color11 #f9e2af
# Blue
color4  #89b4fa
color12 #89b4fa
# Magenta
color5  #f5c2e7
color13 #f5c2e7
# Cyan
color6  #94e2d5
color14 #94e2d5
# White
color7  #bac2de
color15 #a6adc8
# --- Keyboard Shortcuts ---
# Map Ctrl+Shift+h to open the entire scrollback buffer in Neovim
scrollback_pager nvim -c "set signcolumn=no showtabline=0" -c "silent! %s/\u001b\[[0-9;]*m//g" -c "normal G" -
scrollback_lines 2000
map ctrl+shift+h show_scrollback
# --- Tab Mappings ---
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+n next_tab
map alt+p previous_tab
# Quick-select and open URLs
map ctrl+shift+u kitten hints --type url
# Quick-select and copy paths to clipboard
map ctrl+shift+p kitten hints --type path --program @
# Reload config on the fly
map ctrl+shift+f5 load_config_file
# OPen Tmux with kitty term keybid
map ctrl+shift+I launch --type=tab sh -c "tmux a || tmux"
